-- AlterTable
ALTER TABLE "Session" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "focusOverlapTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pomodoroActiveTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "voiceActiveTime" INTEGER NOT NULL DEFAULT 0;
